# Generated by Django 5.1.6 on 2025-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_filterword'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='cover_height',
            field=models.IntegerField(default=400, verbose_name='封面高度'),
        ),
        migrations.AddField(
            model_name='novel',
            name='cover_width',
            field=models.IntegerField(default=300, verbose_name='封面宽度'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='标题'),
        ),
    ]
