# Generated by Django 5.1.6 on 2025-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_remove_novel_cover_height_remove_novel_cover_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'id'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
