# Generated by Django 5.1.6 on 2025-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_chapter_options_chapter_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
    ]
