# Generated by Django 5.1.6 on 2025-02-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_novel_default_cover_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='default_cover_path',
        ),
    ]
